# Generated by Django 3.1.7 on 2021-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210316_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
