# Generated by Django 3.1.7 on 2021-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
