# Generated by Django 3.1.7 on 2021-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210316_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
