# Generated by Django 3.1.7 on 2021-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210316_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'BreakFast'), ('2nd Breakfast', '2nd BreakFast'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Supper', 'Supper')], max_length=13),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
